name: Secretpad Error Issue Template
description: If your question involves issues with the SecretPad platform itself or secondary development requirements, please use this template
body:
  - type: markdown
    attributes:
      value: |
        Please make sure that you report a Install/Deploy Problem, Running Problem on GitHub.
        Please post on our [discussions](https://github.com/secretflow/secretpad/discussions) instead if you want to ask questions or share ideas.
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of issue would you like to report?
      multiple: false
      options:
        - Install/Deploy Problem
        - Running Problem
        - Others
    validations:
      required: true
  - type: dropdown
    id: searched-for-existing-issues
    attributes:
      label: Have you searched for existing documents and issues? 
      description: Existing [documents](https://www.secretflow.org.cn/zh-CN/docs/secretpad/v0.6.0b0/) and [issues](https://github.com/secretflow/secretpad/issues)
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
  - type: input
    id: OS
    attributes:
      label: OS Platform and Distribution
      description:
      placeholder: e.g., Linux Ubuntu 18.04
    validations:
      required: true
  - type: input
    id: all_in_one-version
    attributes:
      label: All_in_one Version
      description:
      placeholder: e.g., v0.6.0b0
    validations:
      required: true
  - type: input
    id: kuscia-version
    attributes:
      label: Kuscia Version
      description:
      placeholder: e.g., kuscia 0.7.0b0
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happend and What you expected to happen.
      description: Describe the bug, expected behavior.
      placeholder: A bug happened!
      value:
      render: shell
    validations:
      required: true
  - type: textarea
    id: log-output
    attributes:
      label: Log output.
      description: Relevant log output
      placeholder: |
        Relevant log output
      value:
      render: shell
    validations:
      required: true
