spring:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
springdoc:
  api-docs:
    enabled: true

kusciaapi:
  address: 127.0.0.1:18083
  tls:
    cert-file: config/certs/client.crt
    key-file: config/certs/client.pem
    ca-file: config/certs/ca.crt
  token-file: config/certs/token

kusciaapi-lite-alice:
  address: 127.0.0.1:8061
  tls:
    cert-file: config/certs/alice/ca.crt
    key-file: config/certs/alice/client.pem
    ca-file: config/certs/alice/client.crt
  token-file: config/certs/alice/token

kusciaapi-lite-bob:
  address: 127.0.0.1:8061
  tls:
    cert-file: config/certs/bob/ca.crt
    key-file: config/certs/bob/client.pem
    ca-file: config/certs/bob/client.crt
  token-file: config/certs/bob/token

secretpad:
  center-platform-service: secretpad.master.svc
  gateway: ${KUSCIA_GW_ADDRESS:127.0.0.1:8080}
  auth:
    enabled: false
  data:
    dir-path: ../tmp/data/
  datasync:
    center: false
    p2p: true
